version: '3.5'

services:
  web:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    container_name: web3
    networks: 
     - default
    ports:
      - '8083:80' # expose 80 on host and sent to 80 in container
    volumes:
            #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html
networks:
  default:
   name: my-bridge-network    
