version: '3.5'

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
      # image: haproxy # this will use the latest version of 1.13.x
    container_name: myubuntu
    networks:
     - default

    ports:
      - '8989:80' # expose 80 on host and sent to 80 in container
            #   - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  default:
   name: my-bridge-network

